/*
 * The board, restructured.
 *
 * Craigslist's front page is an index: nine sections, each a list of
 * subcategories, for one city. The sections and their subcategories are the
 * San Francisco board's as of 3 September 2026, so the counts on the chips
 * come from the lists rather than being typed in.
 */

export const CHAPTERS = [
  { id: "board", number: "01", title: "Board" },
  { id: "listings", number: "02", title: "Listings" },
  { id: "listing", number: "03", title: "Listing" },
  { id: "post", number: "04", title: "Post" },
] as const;

export const CITY = "San Francisco";

export const TODAY = "Sep 03 2026";

/** The Bay Area's sub-regions, as Craigslist abbreviates them. The first is current. */
export const REGIONS = [
  { code: "SFC", name: "City of San Francisco" },
  { code: "SBY", name: "South Bay" },
  { code: "EBY", name: "East Bay" },
  { code: "PEN", name: "Peninsula" },
  { code: "NBY", name: "North Bay" },
  { code: "SCZ", name: "Santa Cruz" },
] as const;

export const HEADLINE = ["Everything", "in the Bay,", "since 1995."] as const;

export const LEAD =
  "Nine sections. Every neighborhood from the Presidio to the Mission, plus the rest of the Bay one chip away. No account needed to browse. Post anything in under a minute.";

export type Section = {
  id: string;
  title: string;
  /** Every subcategory, in the board's order. */
  subcategories: readonly string[];
  /** Which of them the board shows before the chip; the rest are behind it. */
  shown: number;
};

export const SECTIONS: readonly Section[] = [
  {
    id: "community",
    title: "Community",
    shown: 6,
    subcategories: [
      "Activities",
      "Artists",
      "Childcare",
      "Classes",
      "Events",
      "General",
      "Groups",
      "Local news",
      "Lost + found",
      "Missed connections",
      "Musicians",
      "Pets",
      "Politics",
      "Rants & raves",
      "Rideshare",
      "Volunteers",
    ],
  },
  {
    id: "services",
    title: "Services",
    shown: 6,
    subcategories: [
      "Automotive",
      "Beauty",
      "Cell / mobile",
      "Computer",
      "Creative",
      "Cycle",
      "Event",
      "Farm + garden",
      "Financial",
      "Health / well",
      "Household",
      "Labor / move",
      "Legal",
      "Lessons",
      "Marine",
      "Pet",
      "Real estate",
      "Skilled trade",
      "Sm biz ads",
      "Travel / vac",
      "Write / ed / tran",
    ],
  },
  {
    id: "forums",
    title: "Forums",
    shown: 6,
    subcategories: [
      "Apple",
      "Arts",
      "Atheist",
      "Autos",
      "Beauty",
      "Bikes",
      "Celebs",
      "Comp",
      "Cosmos",
      "Diet",
      "Divorce",
      "Dying",
      "Eco",
      "Feedbk",
      "Film",
      "Fixit",
      "Food",
      "Frugal",
      "Gaming",
      "Garden",
      "Haiku",
      "Help",
      "History",
      "Housing",
      "Jobs",
      "Jokes",
      "Legal",
      "Manners",
      "Marriage",
      "Money",
      "Music",
      "Open",
      "Parent",
      "Pets",
      "Philos",
      "Photo",
      "Politics",
      "Psych",
      "Recover",
      "Religion",
      "Rofo",
      "Science",
      "Spirit",
      "Sports",
      "Super",
      "Tax",
      "Travel",
      "TV",
      "Vegan",
      "Words",
      "Writing",
    ],
  },
  {
    id: "housing",
    title: "Housing",
    shown: 6,
    subcategories: [
      "Apts / housing",
      "Housing swap",
      "Office / commercial",
      "Parking / storage",
      "Real estate for sale",
      "Rooms / shared",
      "Rooms wanted",
      "Sublets / temporary",
      "Vacation rentals",
      "Wanted: apts",
      "Wanted: real estate",
      "Wanted: sublet / temp",
    ],
  },
  {
    id: "autos",
    title: "Autos",
    shown: 6,
    subcategories: [
      "ATV / UTV / sno",
      "Auto parts",
      "Aviation",
      "Boat parts",
      "Boats",
      "Cars + trucks",
      "Heavy equip",
      "Motorcycle parts",
      "Motorcycles",
      "RVs + camp",
      "Trailers",
      "Wheels + tires",
    ],
  },
  {
    id: "for-sale",
    title: "For sale",
    shown: 6,
    subcategories: [
      "Antiques",
      "Appliances",
      "Arts + crafts",
      "Baby + kid",
      "Barter",
      "Beauty + hlth",
      "Bike parts",
      "Bikes",
      "Books",
      "Business",
      "CDs / DVD / VHS",
      "Cell phones",
      "Clothes + acc",
      "Collectibles",
      "Computer parts",
      "Computers",
      "Electronics",
      "Farm + garden",
      "Free",
      "Furniture",
      "Garage sale",
      "General",
      "Household",
      "Jewelry",
      "Materials",
      "Music instr",
      "Photo + video",
      "Sporting",
      "Tickets",
      "Tools",
      "Toys + games",
      "Video gaming",
      "Wanted",
    ],
  },
  {
    id: "jobs",
    title: "Jobs",
    shown: 6,
    subcategories: [
      "Accounting + finance",
      "Admin / office",
      "Arch / engineering",
      "Art / media / design",
      "Biotech / science",
      "Business / mgmt",
      "Customer service",
      "Education",
      "Etc / misc",
      "Food / bev / hosp",
      "General labor",
      "Government",
      "Human resources",
      "Legal / paralegal",
      "Manufacturing",
      "Marketing / PR / ad",
      "Medical / health",
      "Nonprofit sector",
      "Real estate",
      "Retail / wholesale",
      "Sales / biz dev",
      "Salon / spa / fitness",
      "Security",
      "Skilled trade / craft",
      "Software / QA / DBA",
      "Systems / network",
      "Technical support",
      "Transport",
      "TV / film / video",
      "Web / info design",
      "Writing / editing",
    ],
  },
  {
    id: "gigs",
    title: "Gigs",
    shown: 6,
    subcategories: [
      "Computer",
      "Creative",
      "Crew",
      "Domestic",
      "Event",
      "Labor",
      "Talent",
      "Writing",
    ],
  },
  {
    id: "resumes",
    title: "Resumes",
    shown: 2,
    subcategories: ["Post a resume", "Browse resumes"],
  },
];

export const FOOTER_LINKS = ["Help", "Safety", "About"] as const;

/** Hyde Street, 2007. Wikimedia Commons serves it, as with the encyclopedia's figures. */
export const PHOTO = {
  src: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Cable_Car_in_San_Francisco.jpg/1280px-Cable_Car_in_San_Francisco.jpg",
  alt: "A cable car conductor, in silhouette, smoking a pipe on the Powell line in San Francisco.",
  caption: "Hyde Street, San Francisco",
  credit: "Hank Miller",
  license: "CC BY-SA 3.0",
  licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
  sourceUrl: "https://commons.wikimedia.org/wiki/File:Cable_Car_in_San_Francisco.jpg",
} as const;
